/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      // Colours are CSS variables (see src/styles/globals.css) so dark mode can swap the palette.
      colors: {
        surface: {
          0: 'rgb(var(--c-surface-0) / <alpha-value>)',
          50: 'rgb(var(--c-surface-50) / <alpha-value>)',
          100: 'rgb(var(--c-surface-100) / <alpha-value>)',
          200: 'rgb(var(--c-surface-200) / <alpha-value>)',
          300: 'rgb(var(--c-surface-300) / <alpha-value>)',
          400: 'rgb(var(--c-surface-400) / <alpha-value>)',
          500: 'rgb(var(--c-surface-500) / <alpha-value>)',
          600: 'rgb(var(--c-surface-600) / <alpha-value>)',
          700: 'rgb(var(--c-surface-700) / <alpha-value>)',
          800: 'rgb(var(--c-surface-800) / <alpha-value>)',
          900: 'rgb(var(--c-surface-900) / <alpha-value>)',
          950: 'rgb(var(--c-surface-950) / <alpha-value>)',
        },
        brand: {
          50: 'rgb(var(--c-brand-50) / <alpha-value>)',
          100: 'rgb(var(--c-brand-100) / <alpha-value>)',
          200: 'rgb(var(--c-brand-200) / <alpha-value>)',
          300: 'rgb(var(--c-brand-300) / <alpha-value>)',
          400: 'rgb(var(--c-brand-400) / <alpha-value>)',
          500: 'rgb(var(--c-brand-500) / <alpha-value>)',
          600: 'rgb(var(--c-brand-600) / <alpha-value>)',
          700: 'rgb(var(--c-brand-700) / <alpha-value>)',
          800: 'rgb(var(--c-brand-800) / <alpha-value>)',
          900: 'rgb(var(--c-brand-900) / <alpha-value>)',
          950: 'rgb(var(--c-brand-950) / <alpha-value>)',
        },
        success: {
          50: 'rgb(var(--c-success-50) / <alpha-value>)',
          100: 'rgb(var(--c-success-100) / <alpha-value>)',
          200: 'rgb(var(--c-success-200) / <alpha-value>)',
          500: 'rgb(var(--c-success-500) / <alpha-value>)',
          600: 'rgb(var(--c-success-600) / <alpha-value>)',
          700: 'rgb(var(--c-success-700) / <alpha-value>)',
          800: 'rgb(var(--c-success-800) / <alpha-value>)',
        },
        warning: {
          50: 'rgb(var(--c-warning-50) / <alpha-value>)',
          100: 'rgb(var(--c-warning-100) / <alpha-value>)',
          200: 'rgb(var(--c-warning-200) / <alpha-value>)',
          500: 'rgb(var(--c-warning-500) / <alpha-value>)',
          600: 'rgb(var(--c-warning-600) / <alpha-value>)',
          700: 'rgb(var(--c-warning-700) / <alpha-value>)',
          800: 'rgb(var(--c-warning-800) / <alpha-value>)',
        },
        danger: {
          50: 'rgb(var(--c-danger-50) / <alpha-value>)',
          100: 'rgb(var(--c-danger-100) / <alpha-value>)',
          200: 'rgb(var(--c-danger-200) / <alpha-value>)',
          400: 'rgb(var(--c-danger-400) / <alpha-value>)',
          500: 'rgb(var(--c-danger-500) / <alpha-value>)',
          600: 'rgb(var(--c-danger-600) / <alpha-value>)',
          700: 'rgb(var(--c-danger-700) / <alpha-value>)',
          800: 'rgb(var(--c-danger-800) / <alpha-value>)',
        },
        info: {
          50: 'rgb(var(--c-info-50) / <alpha-value>)',
          100: 'rgb(var(--c-info-100) / <alpha-value>)',
          200: 'rgb(var(--c-info-200) / <alpha-value>)',
          500: 'rgb(var(--c-info-500) / <alpha-value>)',
          600: 'rgb(var(--c-info-600) / <alpha-value>)',
          700: 'rgb(var(--c-info-700) / <alpha-value>)',
        },
        purple: {
          50: 'rgb(var(--c-purple-50) / <alpha-value>)',
          100: 'rgb(var(--c-purple-100) / <alpha-value>)',
          200: 'rgb(var(--c-purple-200) / <alpha-value>)',
          600: 'rgb(var(--c-purple-600) / <alpha-value>)',
          700: 'rgb(var(--c-purple-700) / <alpha-value>)',
        },
        orange: {
          50: 'rgb(var(--c-orange-50) / <alpha-value>)',
          100: 'rgb(var(--c-orange-100) / <alpha-value>)',
          200: 'rgb(var(--c-orange-200) / <alpha-value>)',
          600: 'rgb(var(--c-orange-600) / <alpha-value>)',
          700: 'rgb(var(--c-orange-700) / <alpha-value>)',
          800: 'rgb(var(--c-orange-800) / <alpha-value>)',
        },
        cyan: {
          50: 'rgb(var(--c-cyan-50) / <alpha-value>)',
          100: 'rgb(var(--c-cyan-100) / <alpha-value>)',
          600: 'rgb(var(--c-cyan-600) / <alpha-value>)',
          700: 'rgb(var(--c-cyan-700) / <alpha-value>)',
        },
        violet: {
          50: 'rgb(var(--c-violet-50) / <alpha-value>)',
          600: 'rgb(var(--c-violet-600) / <alpha-value>)',
        },
        pink: {
          100: 'rgb(var(--c-pink-100) / <alpha-value>)',
          700: 'rgb(var(--c-pink-700) / <alpha-value>)',
        },
        indigo: {
          50: 'rgb(var(--c-indigo-50) / <alpha-value>)',
          600: 'rgb(var(--c-indigo-600) / <alpha-value>)',
        },
        card: 'rgb(var(--c-card) / <alpha-value>)',
      },
      fontFamily: {
        sans: [
          'Inter',
          'ui-sans-serif',
          'system-ui',
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          'Roboto',
          '"Helvetica Neue"',
          'Arial',
          '"Noto Sans"',
          'sans-serif',
        ],
        mono: [
          '"JetBrains Mono"',
          '"Fira Code"',
          'ui-monospace',
          'SFMono-Regular',
          'Menlo',
          'Monaco',
          'Consolas',
          '"Liberation Mono"',
          '"Courier New"',
          'monospace',
        ],
      },
      fontSize: {
        '2xs': ['0.625rem', { lineHeight: '0.875rem' }],
      },
      spacing: {
        18: '4.5rem',
        72: '18rem',
        80: '20rem',
        88: '22rem',
        96: '24rem',
      },
      borderRadius: {
        '4xl': '2rem',
      },
      boxShadow: {
        'soft-sm': '0 1px 3px 0 rgb(0 0 0 / 0.05), 0 1px 2px -1px rgb(0 0 0 / 0.05)',
        soft: '0 4px 6px -1px rgb(0 0 0 / 0.07), 0 2px 4px -2px rgb(0 0 0 / 0.07)',
        'soft-md': '0 10px 15px -3px rgb(0 0 0 / 0.07), 0 4px 6px -4px rgb(0 0 0 / 0.07)',
        'soft-lg': '0 20px 25px -5px rgb(0 0 0 / 0.07), 0 8px 10px -6px rgb(0 0 0 / 0.07)',
        'soft-xl': '0 25px 50px -12px rgb(0 0 0 / 0.15)',
        'inner-soft': 'inset 0 1px 3px 0 rgb(0 0 0 / 0.06)',
      },
      animation: {
        'fade-in': 'fadeIn 0.2s ease-in-out',
        'slide-up': 'slideUp 0.2s ease-out',
        'slide-down': 'slideDown 0.2s ease-out',
        'slide-in-left': 'slideInLeft 0.25s ease-out',
        'spin-slow': 'spin 3s linear infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideDown: {
          '0%': { opacity: '0', transform: 'translateY(-8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideInLeft: {
          '0%': { opacity: '0', transform: 'translateX(-100%)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
      },
      transitionTimingFunction: {
        spring: 'cubic-bezier(0.175, 0.885, 0.32, 1.275)',
      },
      screens: {
        xs: '480px',
      },
      zIndex: {
        60: '60',
        70: '70',
        80: '80',
        90: '90',
        100: '100',
      },
    },
  },
  plugins: [],
};
